//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeRestReminder {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeRestReminder.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ready to work benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppReady {
            get {
                return ResourceManager.GetString("AppReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye Rest Reminder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music or video is playing benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AudioPlaying {
            get {
                return ResourceManager.GetString("AudioPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run at startup benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No activity detected benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IdleText {
            get {
                return ResourceManager.GetString("IdleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard or mouse is being used benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseKeyboard {
            get {
                return ResourceManager.GetString("MouseKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20 minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reminder20Text {
            get {
                return ResourceManager.GetString("Reminder20Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30 minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reminder30Text {
            get {
                return ResourceManager.GetString("Reminder30Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   40 minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reminder40Text {
            get {
                return ResourceManager.GetString("Reminder40Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50 minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reminder50Text {
            get {
                return ResourceManager.GetString("Reminder50Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reminder Interval benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReminderIntervalMenu {
            get {
                return ResourceManager.GetString("ReminderIntervalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reminder interval set to {0} minutes. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReminderIntervalSetMsg {
            get {
                return ResourceManager.GetString("ReminderIntervalSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every 20 minutes, look at something 20 feet (6 meters) away for 20 seconds. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReminderMessage {
            get {
                return ResourceManager.GetString("ReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time for a 20-second eye rest! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume timer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ResumeText {
            get {
                return ResourceManager.GetString("ResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show window benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShowStatus {
            get {
                return ResourceManager.GetString("ShowStatus", resourceCulture);
            }
        }
    }
}
